module.exports = {
  collectCoverage: true,
  collectCoverageFrom: [
    'src/routes/auth.js',
    'src/routes/requests.js',
    'src/middleware/auth.js',
    'src/middleware/authorize.js',
    'src/middleware/idempotency.js',
    'src/middleware/platformAuth.js',
    'src/middleware/propertyDb.js',
    'src/sse.js',
    'src/sse-redis.js',
    'src/v1/lib/authz.js',
    'src/v1/routes/accessIncidents.js',
    'src/v1/routes/accessPolicies.js',
    'src/v1/routes/accessRequests.js',
    'src/v1/routes/accessTopology.js',
    'src/v1/routes/securityWorkspace.js',
    'src/v1/routes/vehicles.js',
    'src/v1/routes/announcements.js',
    'src/v1/routes/documents.js',
    'src/v1/routes/packages.js',
    'src/v1/routes/adminOutbox.js',
    'src/v1/services/accessActorResolver.js',
    'src/v1/services/accessIncidentService.js',
    'src/v1/services/accessPolicyService.js',
    'src/v1/services/accessRequestService.js',
    'src/v1/services/accessStateMachine.js',
    'src/v1/services/accessTopologyService.js',
    'src/v1/services/securityWorkspaceService.js',
    'src/v1/services/vehicleService.js',
    'src/v1/services/verifyPass.js',
  ],
  coverageThreshold: {
    global: {
      statements: 59,
      branches: 50,
      functions: 70,
      lines: 65,
    },
    './src/v1/lib/authz.js': {
      statements: 75,
      branches: 65,
      functions: 75,
      lines: 75,
    },
    './src/v1/services/accessPolicyService.js': {
      statements: 70,
      branches: 60,
      functions: 70,
      lines: 70,
    },
    './src/v1/services/verifyPass.js': {
      statements: 70,
      branches: 60,
      functions: 70,
      lines: 70,
    },
    './src/v1/services/vehicleService.js': {
      statements: 60,
      branches: 60,
      functions: 80,
      lines: 65,
    },
    './src/v1/routes/accessIncidents.js': {
      statements: 15,
      branches: 10,
      functions: 30,
      lines: 20,
    },
    './src/v1/routes/securityWorkspace.js': {
      statements: 55,
      branches: 50,
      functions: 75,
      lines: 60,
    },
    './src/v1/routes/vehicles.js': {
      statements: 30,
      branches: 20,
      functions: 50,
      lines: 35,
    },
  },
  maxWorkers: 1,
  roots: ['<rootDir>/src'],
  testMatch: [
    '**/__tests__/auth.test.js',
    '**/__tests__/auth.coverage.test.js',
    '**/__tests__/requests.test.js',
    '**/__tests__/authorize.test.js',
    '**/__tests__/idempotency.test.js',
    '**/__tests__/idempotency.coverage.test.js',
    '**/__tests__/middleware_auth.test.js',
    '**/__tests__/platformAuth.test.js',
    '**/__tests__/propertyDb.test.js',
    '**/__tests__/legacyShimTenantResolver.test.js',
    '**/__tests__/sse.test.js',
    '**/__tests__/sseRedis.test.js',
    '**/v1/lib/__tests__/authz.test.js',
    '**/__tests__/v1AccessActorResolver.test.js',
    '**/__tests__/v1AccessIncidentService.test.js',
    '**/__tests__/v1AccessIncidentsRoute.test.js',
    '**/__tests__/v1AccessPolicyService.test.js',
    '**/__tests__/v1AccessPoliciesRoutes.test.js',
    '**/__tests__/v1AccessRequestService.test.js',
    '**/__tests__/v1AccessRequestsRoute.test.js',
    '**/__tests__/v1AccessStateMachine.test.js',
    '**/__tests__/v1AccessTopologyService.test.js',
    '**/__tests__/v1AccessTopologyRoutes.test.js',
    '**/__tests__/v1SecurityWorkspaceRoutes.test.js',
    '**/__tests__/v1VehicleService.test.js',
    '**/__tests__/v1VehiclesRoute.test.js',
    '**/__tests__/v1VerifyPassCascade.test.js',
    '**/__tests__/v1VerifyPassOrchestration.test.js',
    '**/__tests__/v1AnnouncementsEndpoint.test.js',
    '**/__tests__/v1DocumentsEndpoint.test.js',
    '**/__tests__/v1PackagesEndpoint.test.js',
    '**/__tests__/v1AdminOutboxEndpoint.test.js',
  ],
  testEnvironment: 'node',
};
