module.exports = {
  collectCoverage: true,
  collectCoverageFrom: [
    'src/routes/auth.js',
    'src/routes/requests.js',
    'src/middleware/auth.js',
    'src/middleware/authorize.js',
    'src/middleware/idempotency.js',
    'src/middleware/platformAuth.js',
    'src/middleware/propertyDb.js',
    'src/sse.js',
    'src/sse-redis.js',
    'src/v1/routes/announcements.js',
    'src/v1/routes/documents.js',
    'src/v1/routes/packages.js',
    'src/v1/routes/adminOutbox.js',
  ],
  coverageThreshold: {
    global: {
      statements: 70,
      branches: 70,
      functions: 70,
      lines: 70,
    },
  },
  maxWorkers: 1,
  roots: ['<rootDir>/src'],
  testMatch: [
    '**/__tests__/auth.test.js',
    '**/__tests__/auth.coverage.test.js',
    '**/__tests__/requests.test.js',
    '**/__tests__/authorize.test.js',
    '**/__tests__/idempotency.test.js',
    '**/__tests__/idempotency.coverage.test.js',
    '**/__tests__/middleware_auth.test.js',
    '**/__tests__/platformAuth.test.js',
    '**/__tests__/propertyDb.test.js',
    '**/__tests__/sse.test.js',
    '**/__tests__/sseRedis.test.js',
    '**/__tests__/v1AnnouncementsEndpoint.test.js',
    '**/__tests__/v1DocumentsEndpoint.test.js',
    '**/__tests__/v1PackagesEndpoint.test.js',
    '**/__tests__/v1AdminOutboxEndpoint.test.js',
  ],
  testEnvironment: 'node',
};
