export const REQUESTS_ACTIONS = new Set<string>([
  'REQUEST_ADD', 'REQUEST_UPDATE', 'REQUEST_DELETE',
  'REQUEST_SET_STATUS', 'REQUEST_ARRIVE', 'REQUESTS_SET_ALL',
  'REQUEST_ACTIVATE_SCHEDULED', 'HISTORY_ADD',
]);
export const CHAT_ACTIONS = new Set<string>([
  'CHAT_SEND', 'CHAT_SET_ALL', 'CHAT_MARK_SEEN', 'CHAT_UPDATE_MESSAGE', 'CHAT_DELETE_MESSAGE',
]);
export const USERS_ACTIONS = new Set<string>([
  'USER_ADD', 'USER_UPDATE', 'USER_DELETE', 'USERS_SET_ALL', 'AVATAR_SET', 'AVATAR_DELETE',
]);
export const PERMS_ACTIONS = new Set<string>(['PERMS_SET', 'TEMPLATE_ADD', 'TEMPLATE_DELETE', 'TEMPLATES_SET']);
export const BLACKLIST_ACTIONS = new Set<string>(['BLACKLIST_ADD', 'BLACKLIST_REMOVE', 'BLACKLIST_SET_ALL']);
export const GARAGE_ACTIONS = new Set<string>(['GARAGE_ADD_CAR', 'GARAGE_UPDATE_CAR', 'GARAGE_DELETE_CAR', 'GARAGE_SET']);
