import {
  REQUEST_SET_STATUS,
  REQUEST_ARRIVE,
  HISTORY_ADD,
} from './requestActionTypes';

export const A = {
  REQUEST_ADD: 'REQUEST_ADD', REQUEST_UPDATE: 'REQUEST_UPDATE', REQUEST_DELETE: 'REQUEST_DELETE',
  REQUEST_SET_STATUS, REQUEST_ARRIVE,
  REQUESTS_SET_ALL: 'REQUESTS_SET_ALL', REQUEST_ACTIVATE_SCHEDULED: 'REQUEST_ACTIVATE_SCHEDULED',
  HISTORY_ADD,
  CHAT_SEND: 'CHAT_SEND', CHAT_SET_ALL: 'CHAT_SET_ALL', CHAT_MARK_SEEN: 'CHAT_MARK_SEEN',
  CHAT_UPDATE_MESSAGE: 'CHAT_UPDATE_MESSAGE', CHAT_DELETE_MESSAGE: 'CHAT_DELETE_MESSAGE',
  USER_ADD: 'USER_ADD', USER_UPDATE: 'USER_UPDATE', USER_DELETE: 'USER_DELETE', USERS_SET_ALL: 'USERS_SET_ALL',
  AVATAR_SET: 'AVATAR_SET', AVATAR_DELETE: 'AVATAR_DELETE',
  PERMS_SET: 'PERMS_SET', TEMPLATE_ADD: 'TEMPLATE_ADD', TEMPLATE_DELETE: 'TEMPLATE_DELETE', TEMPLATES_SET: 'TEMPLATES_SET',
  BLACKLIST_ADD: 'BLACKLIST_ADD', BLACKLIST_REMOVE: 'BLACKLIST_REMOVE', BLACKLIST_SET_ALL: 'BLACKLIST_SET_ALL',
  GARAGE_ADD_CAR: 'GARAGE_ADD_CAR', GARAGE_UPDATE_CAR: 'GARAGE_UPDATE_CAR', GARAGE_DELETE_CAR: 'GARAGE_DELETE_CAR', GARAGE_SET: 'GARAGE_SET',
} as const;
